"""Creates all tables from app/models.py against DATABASE_URL. Only for a genuinely fresh
database (a brand new Supabase project, or local dev) that has never run any Alembic
migration: `python -m scripts.init_db` from backend/, then
`alembic stamp head` so Alembic knows this DB is already at the latest schema without
replaying every migration's DDL against tables that already exist.

The real Supabase project already has this schema from before Alembic existed here --
don't run this against it. Instead, one-time only, run `alembic stamp head` against it (the
37469073b317 baseline revision was autogenerated to match this exact Base.metadata, so this
just records "already there," it emits no DDL). Any schema change from now on goes through
`alembic revision --autogenerate -m "..."` + `alembic upgrade head`, not by editing models.py
and re-running this script -- see backend/alembic/README (Alembic's own generated one)."""

from app.db import Base, engine
from app.models import (  # noqa: F401
    ColdEmail,
    DailySummary,
    Invite,
    OAuthCredential,
    Posting,
    Profile,
    Secret,
    User,
    WizardDraft,
)

if __name__ == "__main__":
    Base.metadata.create_all(bind=engine)
    print("Tables created.")
