"""baseline: matches existing create_all schema

Revision ID: 37469073b317
Revises: 
Create Date: 2026-08-18 23:19:45.358607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37469073b317'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cold_emails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('posting_key', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('lane', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('sent_at', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('bounced', sa.String(), nullable=False),
    sa.Column('replied', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cold_emails_user_date', 'cold_emails', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_cold_emails_user_id'), 'cold_emails', ['user_id'], unique=False)
    op.create_index('ix_cold_emails_user_posting_key', 'cold_emails', ['user_id', 'posting_key'], unique=False)
    op.create_table('daily_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('applied_count', sa.Integer(), nullable=False),
    sa.Column('pending_approval_count', sa.Integer(), nullable=False),
    sa.Column('emails_sent', sa.Integer(), nullable=False),
    sa.Column('queued_count', sa.Integer(), nullable=False),
    sa.Column('awaiting_apply_count', sa.Integer(), nullable=False),
    sa.Column('cold_email_scanned', sa.Integer(), nullable=False),
    sa.Column('cold_email_eligible', sa.Integer(), nullable=False),
    sa.Column('cold_email_matched', sa.Integer(), nullable=False),
    sa.Column('cold_email_contacts_found', sa.Integer(), nullable=False),
    sa.Column('total_postings_found', sa.Integer(), nullable=False),
    sa.Column('total_matched', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_daily_summaries_user_date', 'daily_summaries', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_daily_summaries_user_id'), 'daily_summaries', ['user_id'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_code'), 'invites', ['code'], unique=True)
    op.create_table('oauth_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('scopes', sa.String(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('granted_email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('posting_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('lane', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('application_url', sa.String(), nullable=False),
    sa.Column('description_text', sa.Text(), nullable=False),
    sa.Column('matched_terms', sa.String(), nullable=False),
    sa.Column('match_score', sa.Numeric(), nullable=False),
    sa.Column('posted_date', sa.String(), nullable=False),
    sa.Column('remote_type', sa.String(), nullable=False),
    sa.Column('employment_type', sa.String(), nullable=False),
    sa.Column('salary_min', sa.Numeric(), nullable=True),
    sa.Column('salary_max', sa.Numeric(), nullable=True),
    sa.Column('required_years', sa.Integer(), nullable=True),
    sa.Column('reason_held', sa.String(), nullable=False),
    sa.Column('resume_version', sa.String(), nullable=False),
    sa.Column('resume_link', sa.String(), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=False),
    sa.Column('content_flags', sa.String(), nullable=False),
    sa.Column('application_status', sa.String(), nullable=False),
    sa.Column('contact_emailed', sa.String(), nullable=False),
    sa.Column('email_sent_at', sa.String(), nullable=False),
    sa.Column('dismissed_at', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status_history', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'posting_key', name='uq_postings_user_posting_key')
    )
    op.create_index(op.f('ix_postings_user_id'), 'postings', ['user_id'], unique=False)
    op.create_index('ix_postings_user_status', 'postings', ['user_id', 'status'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('sheet_id', sa.String(), nullable=False),
    sa.Column('gmail_address', sa.String(), nullable=False),
    sa.Column('report_email', sa.String(), nullable=False),
    sa.Column('adzuna_country', sa.String(), nullable=False),
    sa.Column('apply_daily_cap', sa.Integer(), nullable=False),
    sa.Column('github_repo', sa.String(), nullable=False),
    sa.Column('run_hour_utc', sa.Integer(), nullable=False),
    sa.Column('lanes_json', sa.JSON(), nullable=False),
    sa.Column('cold_email_json', sa.JSON(), nullable=False),
    sa.Column('applicant_json', sa.JSON(), nullable=False),
    sa.Column('greenhouse_boards_json', sa.JSON(), nullable=False),
    sa.Column('lever_companies_json', sa.JSON(), nullable=False),
    sa.Column('ashby_boards_json', sa.JSON(), nullable=False),
    sa.Column('target_countries_json', sa.JSON(), nullable=False),
    sa.Column('resumes_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('secrets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key_name', sa.String(), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wizard_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('draft_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wizard_drafts')
    op.drop_table('secrets')
    op.drop_table('profiles')
    op.drop_index('ix_postings_user_status', table_name='postings')
    op.drop_index(op.f('ix_postings_user_id'), table_name='postings')
    op.drop_table('postings')
    op.drop_table('oauth_credentials')
    op.drop_index(op.f('ix_invites_code'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_daily_summaries_user_id'), table_name='daily_summaries')
    op.drop_index('ix_daily_summaries_user_date', table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_index('ix_cold_emails_user_posting_key', table_name='cold_emails')
    op.drop_index(op.f('ix_cold_emails_user_id'), table_name='cold_emails')
    op.drop_index('ix_cold_emails_user_date', table_name='cold_emails')
    op.drop_table('cold_emails')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
